server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fs_risk_management
    name: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  data:
    elasticsearch:
      host: 127.0.0.1
      port: 9200
      username: elasticsearch
      password:
jdbc:
  pool:
    validationQuery: SELECT 1
  url: jdbc:mysql://localhost:3306/fs_risk_management
  username: root
  password:

application:
  env: dev

redis:
  host: localhost
  port: 6379
  password: 123456
  connect:
    timeout: 0

elasticsearch:
  host: 127.0.0.1
  port: 9200
  cluster-name: docker-cluster  #这里在es的配置文件查，要保证cluster-name与配置文件相同